<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC143191" name="com.mop.qa.test.bvt.Test_Appium_DesktopWeb" tests="1" failures="0" timestamp="19 Aug 2015 11:13:45 GMT" time="39.547" errors="1">
  <testcase name="testDesktop" time="39.547" classname="com.mop.qa.test.bvt.Test_Appium_DesktopWeb">
    <error type="junit.framework.AssertionFailedError" message="Exception in clicking theriyatha button">
      <![CDATA[junit.framework.AssertionFailedError: Exception in clicking theriyatha button
	at com.mop.qa.test.bvt.ReportGenerator.fnResultWriteException(ReportGenerator.java:190)
	at com.mop.qa.testbase.PageBase_Appium.clickbyid(PageBase_Appium.java:294)
	at com.mop.qa.pageobject.Appium_Android_Web.clickSignIn(Appium_Android_Web.java:39)
	at com.mop.qa.test.bvt.Test_Appium_DesktopWeb.testDesktop(Test_Appium_DesktopWeb.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testDesktop -->
</testsuite> <!-- com.mop.qa.test.bvt.Test_Appium_DesktopWeb -->
